### ISSUE TITLE
Target netstandard 2.0

### ISSUE THREAD

**Issue by iron9light** [akkadotnet/HOCON#107]
Based on this doc: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

+ DO start with including a netstandard2.0 target.

> Most general-purpose libraries should not need APIs outside of .NET Standard 2.0. .NET Standard 2.0 is supported by all modern platforms and is the recommended way to support multiple platforms with one target.

+ AVOID including a netstandard1.x target.

> .NET Standard 1.x is distributed as a granular set of NuGet packages, which creates a large package dependency graph and results in developers downloading a lot of packages when building. Modern .NET platforms, including .NET Framework 4.6.1, UWP and Xamarin, all support .NET Standard 2.0. You should only target .NET Standard 1.x if you specifically need to target an older platform.

**Comment by clehene** [comment]
This would prevent downstream libraries to support 1.x and would hinder adoption of new versions. In fact this is the case with `hocon.configuration` - we're stuck to 1.0.0

**Comment by Aaronontheweb** [comment]
There's not really much benefit to this library targeting a higher version of .NET Standard than what it supports right now. We don't use much in the way of platform features, other than maybe reading from the file system - everything else is largely home-grown string manipulation APIs. Sticking with a lower .NET Standard target allows for developers running on legacy runtimes to use us easily, so I think we'll stick with that until there comes a point where we need to adopt a higher version of the standard.

This is the issue we're having with Akka.NET itself right now, actually - in order for us to take advantage of improvements in Socket I/O, serialization, memory management, TPL APIs, and so on we have to move onto a higher version of .NET Standard (1.6 -> 2.0) and we'll have to do another release in the future where we can use 2.1. 

But I don't see the HOCON library having that issue - it mostly just does text parsing at startup to retrieve values and then that's about it. It should target the lowest common denominator and stay there unless there's some other ecosystem change that necessitates upgrading in the future.
