### ISSUE TITLE
Setup CI with Travis

### ISSUE THREAD

**Issue by haighis** [akkadotnet/HOCON#11]

**Comment by Aaronontheweb** [comment]
We can run this on the same build-server as all of the other Akka.NET stuff if you'd like... But honestly,I think it'd be really cool to see this up and running on Travis even though I think .NET support is still in beta there. I'd love to know how to configure a project to run there :)

**Comment by jhaigh** [comment]
I will take a stab at getting this to run under travis with .net.

**Comment by haighis** [comment]
Steps for configuration that I can partially do where the setup aspect on travis ci needs to be done an admin of the hocon gh repo.

[ ] Sign in to Travis CI with your GitHub account, accepting the GitHub access permissions confirmation.
[ ] Once you’re signed in, and travis ci has synchronized your repositories from GitHub, go to your profile page and enable Travis CI for the repository you want to build.

*** Note: You can only enable Travis CI builds for repositories you have admin access to. ***

[ ] Add a .travis.yml to the root directory
```
language: csharp
solution: solution-name.sln
```

**Comment by haighis** [comment]
I assigned this issue to @Aaronontheweb to do these bits:

- [ ] Sign in to Travis CI with your GitHub account, accepting the GitHub access permissions confirmation.
- [ ] Once you’re signed in, and travis ci has synchronized your repositories from GitHub, go to your profile page and enable Travis CI for the repository you want to build.

**Comment by Aaronontheweb** [comment]
Ok dokey, thanks @haighis - will do

**Comment by Aaronontheweb** [comment]
Done!

**Comment by Aaronontheweb** [comment]
https://travis-ci.org/akkadotnet/HOCON
