### ISSUE TITLE
Array is not being substituted correctly

### ISSUE THREAD

**Issue by nareshj09** [akkadotnet/HOCON#127]
Parsing this using akkadotnet
```
    c: {
        q: {
            𝗮: [𝟮, 𝟱]
        }
    }
    c: {
        m: ${c.q} {a: [6]}
    }
```
Results in:
(c.q.a should has changed)
```
    {
        c : {
            q : {
                𝗮 : [𝟲]
            },
            m : {
                a : [6]
            }
        }
    }
```

EXPECTED:
c.q.a should be unchanged

```
    {
        c : {
            q : {
                𝗮 : [𝟮, 𝟱]
            },
            m : {
                a : [6]
            }
        }
    }
```

**Comment by IgorFedchenko** [comment]
Seems like this is not only related to arrays.
I.e. for this config:
```
c: {
    q: {
        a: 1
    }
}
c: {
    m: ${c.q} {a: 2}
}
```

It is also rewriting `c.q.a` to 2, but should not. 
Seems like whenever there is a concatenation with substitution, we have to make full copy of substituted value to make it change safely.

**Comment by IgorFedchenko** [comment]
Interesting fact is that with the following config it works correctly:
```
c: {
    q: {
        a: [2, 5]
    }
    m: ${c.q} {a: [6]}
}
```
