### ISSUE TITLE
Substitution fallback to environment variables and other values

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/HOCON#14]
Make it possible to add named values that can be used for substitutions.
According to Hocon spec, any substitution that is not found in the document itself, could fallback to external values.

``` javascript
foo {
    bar : ${environment.temp-path}
}
```

In this case, `environment.temp-path` could be substituted with an environment variable

**Comment by rogeralsing** [comment]
I'd like to see a way to fallback to web/app config keys too.
e.g. `${config.somekey}`

**Comment by Danthar** [comment]
:+1:
