### ISSUE TITLE
Conventional configuration files

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/HOCON#159]
Being a "C# implementation of Lightbend's HOCON", what's the reasoning for diverging from the convention of loading from files named `application.{conf,json,properties}`  by default?

**Comment by Aaronontheweb** [comment]
Are you referring to https://github.com/akkadotnet/HOCON/issues/48 or is there something else I'm missing?

**Comment by ismaelhamed** [comment]
This is more of a cosmetic issue I guess, but currently `ConfigurationFactory.Default` will only try to load `app.{conf,hocon}` files, whereas Lightbend's loads from `application.{conf,json,properties}`. It is in an  `application.conf` file where you'll traditionally find Akka's configuration in the JVM.

**Comment by Aaronontheweb** [comment]
@Arkatufus guess we should redo this one - liked the original change but it need to go into the `Default()` method, not `Load()`, which has historical consequences
