### ISSUE TITLE
Determine Namespaces: Retain Akka.Configuration & Akka.Configuration.Hocon

### ISSUE THREAD

**Issue by haighis** [akkadotnet/HOCON#16]
How will the namespaces be? 

Do we prevent breaking changes for Akka .NET ( I prefer tthis) by keeping the namespace as Akka.Configuration.Hocon and Akka.Configuration?

**Comment by rogeralsing** [comment]
Our statement to our users have been that the API is frozen for v1 until v2. 
And if the HOCON lib is going to live under the AkkaDotNET organization I think it makes sense to keep the old namespace.

cc @akkadotnet/developers

**Comment by haighis** [comment]
Going to update the namespace to Akka.Configuration, etc. and move all classes back to their structure as they were in akka.
