### ISSUE TITLE
Select test framework for the HOCON tests

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/HOCON#18]
Previously, we have used xUnit for the HOCON tests. 
We have however had a lot of problems with xUnit for the main repo of Akka.NET, so I would be open for switching to e.g. NUnit.

**Comment by SeanKilleen** [comment]
What problems have you had with xUnit? My experience has generally been the reverse. Might be helpful to get some context.

**Comment by Aaronontheweb** [comment]
@SeanKilleen both @stefansedich and myself have had a rather traumatizing experience getting XUnit2 to work on Mono, for starters :p 

Writing the tests themselves isn't the issue - it's more or less that the XUnit test runner itself does a lot of extra stuff under the hood (this is how it appears, at least) that makes it somewhat fragile.

I'm sure if we start using NUnit we'll find some reason to hate it too.

**Comment by haighis** [comment]
Fixed by #21
