### ISSUE TITLE
Simplify current architecture and make it more immutable/serializable

### ISSUE THREAD

**Issue by IgorFedchenko** [akkadotnet/HOCON#205]
Currently entities, that are used in HOCON, are referencing each other via `Parent` and some other properties and one entity can mutate when another entity is changed. You can change state of one entity when opening another entity in the debugger, because "lookup" (or better to say "read") methods actually perform some internal mutations like objects merging and etc.

This complicates code debugging, especially when just calling `ToString` method (or viewing in debugger) can change entity state.

Another issue related with this complexity is that is it hard to serialize such objects with something like Json.NET, since there are lots of cross-references.

Ideally, would be to rewrite HOCON parser and structures in such a way that after parsing we have a tree of immutable structures that are safe to read and modify (that is, create modified copies). Simplifying internal structure will also make easier to serialize/deserialize them.

**Comment by Aaronontheweb** [comment]
@Arkatufus does this one seem done to you as part of 2.0.0?
