### ISSUE TITLE
Hocon as configuration provider for ASP.NET Core

### ISSUE THREAD

**Issue by robertmircea** [akkadotnet/HOCON#219]
Is there any support to user HOCON files/resources as configuration provider for ASP.NET Core? Instead of loading settings from `appsettings.json`, I would like to use a HOCON configuration file.

**Comment by Aaronontheweb** [comment]
@Arkatufus @IgorFedchenko what would we need to create some examples showing how to do this?

**Comment by Arkatufus** [comment]
I've made a sample project on this here: https://github.com/Arkatufus/HoconWebAppSample
