### ISSUE TITLE
Transformations/Tokenization

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/HOCON#245]
I understand that a HOCON file is meant to be immutable, hence the lack of a proper API to modify the file.

So my question is, what would be the proper way of working with transformations/tokenization in a build system, where I want to produce a single artifact (compilation) for multiple deployments and have only the hocon file be *changed* for each deployment --like swapping the whole `akka.persistence` section from a SqlServer configuration to Oracle?

AFAIK, since Lightbend's HOCON library supports Java properties, JSON, and HOCON files, and the ability to merge across them, you could have a separate JSON file where to apply those transformations/tokenization with per-deployment edits and have it loaded and merged back at runtime.

**Comment by Arkatufus** [comment]
You can use `Config.WithFallback()` to override certain parts of HOCON configurations.
For example, if you do `Config _overridenConfig = myOverrideConfig.WithFallback(myDefaultConfig);`, the values in `myOverrideConfig` will overrides the same values in `myDefaultConfig`

**Comment by ismaelhamed** [comment]
That's what I'd like to avoid, having an extra `myOverrideConfig` HOCON file per-customer per-deployment.

**Comment by Arkatufus** [comment]
But that is the correct way of doing it, through configuration, and let the configuration be the single point of truth. If you modify your configuration in code, you might introduce bugs that is hard to track down down the line in production because you can't be sure which configuration is being used, especially if the person that is maintaining the production code is not part of the original development team.

**Comment by Arkatufus** [comment]
By the way, Lightbend `Config` class is also immutable, and you have to use `WithFallback` if you want to merge different configs.

**Comment by ismaelhamed** [comment]
I forgot to close this one, as this is already supported. Via `ParseString` you can load any arbitrary json object that could've been previously transformed during the CI/CD pipeline for instance, and then can be merged back using `WithFallback` during application bootstrap.
