### ISSUE TITLE
Environment variables substitution doesn't work

### ISSUE THREAD

**Issue by dluc** [akkadotnet/HOCON#40]
Reading the documentation I thought environment variables were supported, similarly to the Java version. However a simple test fails, even with the "?" syntax which should silent any error.

application.conf (build action: Content + Copy always):
```
myapp {
	connstring: ${?MY_CONN_STRING}
}
```

Program.cs
```
using Akka.Configuration;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var config = ConfigurationFactory.ParseString(System.IO.File.ReadAllText("application.conf"));
        }
    }
}
```

Result: 
```
Akka.Configuration.Hocon.HoconParserException occurred
  HResult=0x80131500
  Message=Unresolved substitution:
  Source=Akka.Hocon
  StackTrace:
   at Akka.Configuration.Hocon.Parser.ParseText(String text, Func`2 includeCallback)
   at Akka.Configuration.ConfigurationFactory.ParseString(String hocon)
   at ConsoleApp1.Program.Main(String[] args) in Program.cs:line 9
```

I did a quick debug and I found two problems:
* `PullSubstitution` depends on `IsUnquotedText` which calls `!NotInUnquotedText.Contains(Peek())` which returns True for the "?" symbol
  * removing "?" fixes the Substitution token parsing problem, but this means that optional env vars are not supported
* `Parser.ParseValue` never attempts to find an environment variable, and `ResolvedValue` is `null`. It looks like substitutions support only referencing other keys in the same hocon file. This leads to a `null` result to `c.GetValue` in `ParseText` and from there the exception.

**Comment by Arkatufus** [comment]
Should be resolved by https://github.com/akkadotnet/HOCON/pull/47, awaiting approval.
