### ISSUE TITLE
Substitution enviroment variables

### ISSUE THREAD

**Issue by Zetanova** [akkadotnet/HOCON#78]
The substitution for environment variables not working.

ENV AKKATEST=ok

Test code:
var akkTest = Environment.GetEnvironmentVariable("AKKATEST");
Debug.Assert(akkTest == "ok");

Test Config:
akka {
    test = ${AKKATEST}
}

Parsing of the config makes error: 'Unresolved substitution: AKKATEST'

I looked inside the code and it looks ok,
Can it be that the akka main lib is still using a old version of hocon?

**Comment by Zetanova** [comment]
As workaround for akka.net:
Include HOCON as reference and reparse the config:
```
var hr = Hocon.Parser.Parse(loadedConfigString);
var configString = hr.PrettyPrint(2); //ToString gives a ArgumentOutOfRange exception for count
var akkaConfig = Akka.Configuration.ConfigurationFactory.ParseString(configString);
´´´

**Comment by Zetanova** [comment]
There is currently no way to set an array over environment variables.

 it is possiblein akka JVM to set an array with:
env SEED_NODES.0="akka.tcp//cluster@akka-node-0:2551"
env SEED_NODES.1="akka.tcp//cluster@akka-node-1:2551"

**Comment by Zetanova** [comment]
Maybe we can auto-generate hocon section from the 
environment variables and use it as fallback or overload config?

Example:
env akka.cluster.seed-nodes.0 = "akka.tcp//cluster@akka-node-0:2551"
env akka.cluster.seed-nodes.1 = "akka.tcp//cluster@akka-node-2:2551"
env akka.remote.do-netty.tcp.hostname = "akka-node-0"

var config = Hocon.Parser.FromEnvironment("akka");

would generate following hocon config:

akka {
  remote.dot-netty.tcp.hostname = "akka-node-0"
  cluster.seed-nodes = ["akka.tcp//cluster@akka-node-0:2551", "akka.tcp//cluster@akka-node-2:2551"]    
}

It can then be used as overload to the real akka config or as fallback.

If there is some need i would make a PR.

**Comment by Aaronontheweb** [comment]
@Arkatufus whats's our current level of support for this look like?

**Comment by Arkatufus** [comment]
Substitution fallback to environment variable is supported in this branch of HOCON.
[https://github.com/akkadotnet/HOCON/blob/dev/src/Hocon.Tests/Substitution.cs#L89](url)
