### ISSUE TITLE
fully qualified type name with assembly cant be used as property name

### ISSUE THREAD

**Issue by Zetanova** [akkadotnet/HOCON#79]
akka.net is using for some sections like event-adapter and serializer 
"fully qualified type name with assembly" as property names.
Type names includes invalid tokens/characters (like dot and comma) for the property name .

Example:
```
akka {
persistence {
        journal {
          plugin = "akka.persistence.journal.sql-server"
          sql-server {
            class = "Akka.Persistence.SqlServer.Journal.BatchingSqlServerJournal, Akka.Persistence.SqlServer"
            schema-name = dbo
            table-name = EventJournal
            auto-initialize = off
            event-adapters {
              json-adapter = "Demo.EventAdapter, Demo"
            }
            event-adapter-bindings {
              "Demo.IMyEvent" = json-adapter #this line makes a invalid token exception
            }
          }
        } 
}
}
```

**Comment by Arkatufus** [comment]
This is supported in the current HOCON development branch (standalone), waiting for main Akka.Net to adopt the new HOCON library.

**Comment by Arkatufus** [comment]
The exception should not happen in the standalone HOCON library, waiting for the main Akka.Net library to adopt the new HOCON library.
[https://github.com/Arkatufus/HOCON/blob/79_Add_test_for_quoted_key/src/Hocon.Tests/PathTests.cs#L55](url)
[https://github.com/akkadotnet/HOCON/pull/84](url)
