### ISSUE TITLE
rename AkkaConfigurationSection to HoconConfigurationSection?

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/HOCON#8]
https://github.com/akkadotnet/hocon/blob/master/src/core/Hocon/Hocon/AkkaConfigurationSection.cs

Do we want to rename this to something more generic? Like `HoconConfigurationSection`?

**Comment by haighis** [comment]
Yes, I was thinking HoconConfigurationSection as well..

**Comment by Arkatufus** [comment]
This should be closed since its already merged?

**Comment by Aaronontheweb** [comment]
Yep
