### ISSUE TITLE
Setup HOCON nightlies

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/HOCON#85]
Should add HOCON nightlies to our public nightly feed

**Comment by iron9light** [comment]
> The nightly builds are generated nightly at midnight UTC if there have been modifications to the dev branch of Akka.NET since the previous build.
> https://getakka.net/community/getting-access-to-nightly-builds.html#build-frequency-and-details

Does it work with this repo as well?

**Comment by Aaronontheweb** [comment]
Nightlies are now available at https://getakka.net/community/getting-access-to-nightly-builds.html
