### ISSUE TITLE
substitution with itself has bug

### ISSUE THREAD

**Issue by iron9light** [akkadotnet/HOCON#95]
```
a {
  b: [1, 2]
}
a.b: ${a.b} [3, 4]
```
It throw an exception:
Hocon.HoconParserException : Invalid substitution declaration. A cyclic substitution loop is detected in the Hocon file.

**Comment by Arkatufus** [comment]
I'll check it out, thanks.

**Comment by iron9light** [comment]
Failed for this case:
```
a {
  b: [1, 2]
}
a {
  b: ${a.b} [3, 4]
}
```
Hocon.HoconParserException : Unresolved substitution: a.b. At path 'a.b'

**Comment by iron9light** [comment]
@Arkatufus just a reminder to make sure you see the message above.

**Comment by Aaronontheweb** [comment]
Guess we should create a new issue or re-open this?
